# Generated by Django 4.2.3 on 2023-07-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=50)),
                ("passwrd", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="driverz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dname", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("passw", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=50)),
                ("auto_number", models.CharField(max_length=200)),
                ("auto_type", models.CharField(max_length=200)),
                ("auto_date", models.CharField(max_length=200)),
                ("license_no", models.CharField(max_length=200)),
                (
                    "auto_photo",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="images/"
                    ),
                ),
                (
                    "driver_photo",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="images/"
                    ),
                ),
                (
                    "driver_qr",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("froute", models.CharField(max_length=200)),
                ("troute", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="vehical_location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("adress", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "map_location",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_admin.driverz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ride_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("froute", models.CharField(max_length=200)),
                ("troute", models.CharField(max_length=200)),
                ("total_km", models.CharField(max_length=200)),
                ("perkm_cost", models.CharField(max_length=150)),
                ("total_amount", models.CharField(max_length=150)),
                ("book_date", models.CharField(max_length=200)),
                ("book_time", models.CharField(max_length=150)),
                ("book_status", models.CharField(max_length=150)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_admin.customer",
                    ),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_admin.driverz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rbook_id", models.CharField(max_length=150)),
                ("t_type", models.CharField(default=None, max_length=150, null=True)),
                ("t_amount", models.CharField(max_length=150)),
                ("t_date", models.CharField(max_length=150)),
                ("pmtstatus", models.CharField(max_length=150)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_admin.customer",
                    ),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_admin.driverz",
                    ),
                ),
            ],
        ),
    ]
