# Generated by Django 4.2.3 on 2023-07-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="rbook_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auto_admin.ride_book"
            ),
        ),
    ]
